-- ======================================================
-- Task Management App — Database Schema
-- Generated by AIDEN Architect Agent v2
-- Engine: PostgreSQL 16
-- ======================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- ── ENUMS ────────────────────────────────────────────────────
CREATE TYPE task_status   AS ENUM ('todo','in_progress','review','done','cancelled');
CREATE TYPE task_priority AS ENUM ('low','medium','high','urgent');
CREATE TYPE team_role     AS ENUM ('owner','admin','member');

-- ── USERS ────────────────────────────────────────────────────
CREATE TABLE users (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email         VARCHAR(255) UNIQUE NOT NULL,
  password_hash TEXT         NOT NULL,
  name          VARCHAR(100) NOT NULL,
  avatar_url    TEXT,
  is_active     BOOLEAN      NOT NULL DEFAULT true,
  last_login    TIMESTAMPTZ,
  deleted_at    TIMESTAMPTZ,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_users_email      ON users(lower(email));
CREATE INDEX idx_users_active     ON users(is_active) WHERE deleted_at IS NULL;

-- ── TEAMS ────────────────────────────────────────────────────
CREATE TABLE teams (
  id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name       VARCHAR(100) NOT NULL,
  slug       VARCHAR(60)  UNIQUE NOT NULL,
  owner_id   UUID         NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE team_members (
  team_id   UUID      REFERENCES teams(id) ON DELETE CASCADE,
  user_id   UUID      REFERENCES users(id) ON DELETE CASCADE,
  role      team_role NOT NULL DEFAULT 'member',
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (team_id, user_id)
);

-- ── TASKS ────────────────────────────────────────────────────
CREATE TABLE tasks (
  id          UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  title       VARCHAR(500)  NOT NULL,
  description TEXT,
  status      task_status   NOT NULL DEFAULT 'todo',
  priority    task_priority NOT NULL DEFAULT 'medium',
  due_date    DATE,
  tags        TEXT[]        NOT NULL DEFAULT '{}',
  creator_id  UUID          NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  assignee_id UUID          REFERENCES users(id) ON DELETE SET NULL,
  team_id     UUID          REFERENCES teams(id) ON DELETE CASCADE,
  deleted_at  TIMESTAMPTZ,
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_tasks_creator   ON tasks(creator_id)   WHERE deleted_at IS NULL;
CREATE INDEX idx_tasks_assignee  ON tasks(assignee_id)  WHERE deleted_at IS NULL;
CREATE INDEX idx_tasks_status    ON tasks(status)        WHERE deleted_at IS NULL;
CREATE INDEX idx_tasks_priority  ON tasks(priority)      WHERE deleted_at IS NULL;
CREATE INDEX idx_tasks_due       ON tasks(due_date)      WHERE deleted_at IS NULL;
CREATE INDEX idx_tasks_title_trgm ON tasks USING GIN (title gin_trgm_ops);

-- ── AUDIT LOG ────────────────────────────────────────────────
CREATE TABLE audit_log (
  id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  table_name VARCHAR(50)  NOT NULL,
  record_id  UUID         NOT NULL,
  action     VARCHAR(10)  NOT NULL CHECK (action IN ('INSERT','UPDATE','DELETE')),
  user_id    UUID         REFERENCES users(id) ON DELETE SET NULL,
  old_data   JSONB,
  new_data   JSONB,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_audit_record ON audit_log(table_name, record_id);

-- ── TRIGGERS ─────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $$;

CREATE TRIGGER trg_tasks_updated BEFORE UPDATE ON tasks FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_users_updated BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();